# Generated by Django 5.0.7 on 2024-08-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsc_app", "0002_testimonialinfo_quote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="image",
        ),
        migrations.AlterField(
            model_name="teammember",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="linkedin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="pinterest",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="twitter",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
