# Generated by Django 5.0.7 on 2024-08-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsc_app", "0003_remove_teammember_image_alter_teammember_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="team/"),
        ),
    ]
