# Generated by Django 5.0.7 on 2024-08-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsc_app", "0004_teammember_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="blochure",
            field=models.FileField(blank=True, null=True, upload_to="brochures/"),
        ),
    ]
