# Generated by Django 5.0.7 on 2024-08-06 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fsc_app", "0006_tag_ourprojects_challangeandsolution_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ourprojects",
            old_name="ChallangeAndSolution",
            new_name="ChallangeAndSolution_description",
        ),
    ]
