# Generated by Django 5.0.7 on 2024-08-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fsc_app",
            "0007_rename_challangeandsolution_ourprojects_challangeandsolution_description",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images/"),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("subdescription", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("category", models.CharField(max_length=100)),
                ("dailyquote", models.TextField(blank=True, null=True)),
                (
                    "quoteAuthor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tag", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
