# Generated by Django 5.0.7 on 2024-08-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsc_app", "0008_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="tag",
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(blank=True, to="fsc_app.tag"),
        ),
    ]
