# Generated by Django 5.0.7 on 2024-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsc_app", "0009_remove_blog_tag_blog_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image_two",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
