# Generated by Django 5.0.7 on 2025-07-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsc_app', '0011_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='member_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
