# Generated by Django 5.0.7 on 2024-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsc_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonialinfo",
            name="quote",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
