# Generated by Django 5.0.7 on 2024-08-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fsc_app", "0010_blog_image_two"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
